### ISSUE TITLE
“相似度比较阈值”的文档似乎矛盾

### ISSUE THREAD

**Issue by YDX-2147483647** [fishyy119/PPTVideo_to_image#1]
README 似乎暗示“相似度比较阈值”是0到1的小数，而实际实现却是非负/正整数。这是否矛盾？
https://github.com/fishyy119/PPTVideo_to_image/blob/6a0bfe5ea9665af9d58fa1249db7b4d594f99562/README.md?plain=1#L28-L32
https://github.com/fishyy119/PPTVideo_to_image/blob/6a0bfe5ea9665af9d58fa1249db7b4d594f99562/Cpp_branch/src/PV2i.cpp#L254
https://github.com/fishyy119/PPTVideo_to_image/blob/6a0bfe5ea9665af9d58fa1249db7b4d594f99562/Cpp_branch/src/PV2i.cpp#L93
https://github.com/fishyy119/PPTVideo_to_image/blob/6a0bfe5ea9665af9d58fa1249db7b4d594f99562/Cpp_branch/src/PV2i.cpp#L187

**Comment by fishyy119** [comment]
确实没考虑到这样的描述会让人误解比较阈值是[0,1]区间内的小数。

实际上，这里的阈值是汉明距离的阈值，因此就是非负整数。

稍后会完善这里的说明。

**Comment by fishyy119** [comment]
在提交 027b0399d5417a00fe21c8ff9e4bd6675d698403 中进行了完善
